import { h } from "./h";
import { HTMLComponent } from "./types";

export const A: HTMLComponent<"a"> = (props, children) => { return h("a", props, children); }
export const Abbr: HTMLComponent<"abbr"> = (props, children) => { return h("abbr", props, children); }
export const Address: HTMLComponent<"address"> = (props, children) => { return h("address", props, children); }
export const Area: HTMLComponent<"area"> = (props, children) => { return h("area", props, children); }
export const Article: HTMLComponent<"article"> = (props, children) => { return h("article", props, children); }
export const Aside: HTMLComponent<"aside"> = (props, children) => { return h("aside", props, children); }
export const Audio: HTMLComponent<"audio"> = (props, children) => { return h("audio", props, children); }
export const B: HTMLComponent<"b"> = (props, children) => { return h("b", props, children); }
export const Base: HTMLComponent<"base"> = (props, children) => { return h("base", props, children); }
export const Bdi: HTMLComponent<"bdi"> = (props, children) => { return h("bdi", props, children); }
export const Bdo: HTMLComponent<"bdo"> = (props, children) => { return h("bdo", props, children); }
export const Blockquote: HTMLComponent<"blockquote"> = (props, children) => { return h("blockquote", props, children); }
export const Body: HTMLComponent<"body"> = (props, children) => { return h("body", props, children); }
export const Br: HTMLComponent<"br"> = (props, children) => { return h("br", props, children); }
export const Button: HTMLComponent<"button"> = (props, children) => { return h("button", props, children); }
export const Canvas: HTMLComponent<"canvas"> = (props, children) => { return h("canvas", props, children); }
export const Caption: HTMLComponent<"caption"> = (props, children) => { return h("caption", props, children); }
export const Cite: HTMLComponent<"cite"> = (props, children) => { return h("cite", props, children); }
export const Code: HTMLComponent<"code"> = (props, children) => { return h("code", props, children); }
export const Col: HTMLComponent<"col"> = (props, children) => { return h("col", props, children); }
export const Colgroup: HTMLComponent<"colgroup"> = (props, children) => { return h("colgroup", props, children); }
export const Data: HTMLComponent<"data"> = (props, children) => { return h("data", props, children); }
export const Datalist: HTMLComponent<"datalist"> = (props, children) => { return h("datalist", props, children); }
export const Dd: HTMLComponent<"dd"> = (props, children) => { return h("dd", props, children); }
export const Del: HTMLComponent<"del"> = (props, children) => { return h("del", props, children); }
export const Details: HTMLComponent<"details"> = (props, children) => { return h("details", props, children); }
export const Dfn: HTMLComponent<"dfn"> = (props, children) => { return h("dfn", props, children); }
export const Dialog: HTMLComponent<"dialog"> = (props, children) => { return h("dialog", props, children); }
export const Div: HTMLComponent<"div"> = (props, children) => { return h("div", props, children); }
export const Dl: HTMLComponent<"dl"> = (props, children) => { return h("dl", props, children); }
export const Dt: HTMLComponent<"dt"> = (props, children) => { return h("dt", props, children); }
export const Em: HTMLComponent<"em"> = (props, children) => { return h("em", props, children); }
export const Embed: HTMLComponent<"embed"> = (props, children) => { return h("embed", props, children); }
export const Fieldset: HTMLComponent<"fieldset"> = (props, children) => { return h("fieldset", props, children); }
export const Figcaption: HTMLComponent<"figcaption"> = (props, children) => { return h("figcaption", props, children); }
export const Figure: HTMLComponent<"figure"> = (props, children) => { return h("figure", props, children); }
export const Footer: HTMLComponent<"footer"> = (props, children) => { return h("footer", props, children); }
export const Form: HTMLComponent<"form"> = (props, children) => { return h("form", props, children); }
export const H1: HTMLComponent<"h1"> = (props, children) => { return h("h1", props, children); }
export const H2: HTMLComponent<"h2"> = (props, children) => { return h("h2", props, children); }
export const H3: HTMLComponent<"h3"> = (props, children) => { return h("h3", props, children); }
export const H4: HTMLComponent<"h4"> = (props, children) => { return h("h4", props, children); }
export const H5: HTMLComponent<"h5"> = (props, children) => { return h("h5", props, children); }
export const H6: HTMLComponent<"h6"> = (props, children) => { return h("h6", props, children); }
export const Head: HTMLComponent<"head"> = (props, children) => { return h("head", props, children); }
export const Header: HTMLComponent<"header"> = (props, children) => { return h("header", props, children); }
export const Hgroup: HTMLComponent<"hgroup"> = (props, children) => { return h("hgroup", props, children); }
export const Hr: HTMLComponent<"hr"> = (props, children) => { return h("hr", props, children); }
export const Html: HTMLComponent<"html"> = (props, children) => { return h("html", props, children); }
export const I: HTMLComponent<"i"> = (props, children) => { return h("i", props, children); }
export const Iframe: HTMLComponent<"iframe"> = (props, children) => { return h("iframe", props, children); }
export const Img: HTMLComponent<"img"> = (props, children) => { return h("img", props, children); }
export const Input: HTMLComponent<"input"> = (props, children) => { return h("input", props, children); }
export const Ins: HTMLComponent<"ins"> = (props, children) => { return h("ins", props, children); }
export const Kbd: HTMLComponent<"kbd"> = (props, children) => { return h("kbd", props, children); }
export const Label: HTMLComponent<"label"> = (props, children) => { return h("label", props, children); }
export const Legend: HTMLComponent<"legend"> = (props, children) => { return h("legend", props, children); }
export const Li: HTMLComponent<"li"> = (props, children) => { return h("li", props, children); }
export const Link: HTMLComponent<"link"> = (props, children) => { return h("link", props, children); }
export const Main: HTMLComponent<"main"> = (props, children) => { return h("main", props, children); }
export const Map: HTMLComponent<"map"> = (props, children) => { return h("map", props, children); }
export const Mark: HTMLComponent<"mark"> = (props, children) => { return h("mark", props, children); }
export const Menu: HTMLComponent<"menu"> = (props, children) => { return h("menu", props, children); }
export const Meta: HTMLComponent<"meta"> = (props, children) => { return h("meta", props, children); }
export const Meter: HTMLComponent<"meter"> = (props, children) => { return h("meter", props, children); }
export const Nav: HTMLComponent<"nav"> = (props, children) => { return h("nav", props, children); }
export const Noscript: HTMLComponent<"noscript"> = (props, children) => { return h("noscript", props, children); }
export const Ol: HTMLComponent<"ol"> = (props, children) => { return h("ol", props, children); }
export const Optgroup: HTMLComponent<"optgroup"> = (props, children) => { return h("optgroup", props, children); }
export const Option: HTMLComponent<"option"> = (props, children) => { return h("option", props, children); }
export const Output: HTMLComponent<"output"> = (props, children) => { return h("output", props, children); }
export const P: HTMLComponent<"p"> = (props, children) => { return h("p", props, children); }
export const Picture: HTMLComponent<"picture"> = (props, children) => { return h("picture", props, children); }
export const Pre: HTMLComponent<"pre"> = (props, children) => { return h("pre", props, children); }
export const Progress: HTMLComponent<"progress"> = (props, children) => { return h("progress", props, children); }
export const Q: HTMLComponent<"q"> = (props, children) => { return h("q", props, children); }
export const Rp: HTMLComponent<"rp"> = (props, children) => { return h("rp", props, children); }
export const Rt: HTMLComponent<"rt"> = (props, children) => { return h("rt", props, children); }
export const Ruby: HTMLComponent<"ruby"> = (props, children) => { return h("ruby", props, children); }
export const S: HTMLComponent<"s"> = (props, children) => { return h("s", props, children); }
export const Samp: HTMLComponent<"samp"> = (props, children) => { return h("samp", props, children); }
export const Script: HTMLComponent<"script"> = (props, children) => { return h("script", props, children); }
export const Section: HTMLComponent<"section"> = (props, children) => { return h("section", props, children); }
export const Select: HTMLComponent<"select"> = (props, children) => { return h("select", props, children); }
export const Slot: HTMLComponent<"slot"> = (props, children) => { return h("slot", props, children); }
export const Small: HTMLComponent<"small"> = (props, children) => { return h("small", props, children); }
export const Source: HTMLComponent<"source"> = (props, children) => { return h("source", props, children); }
export const Span: HTMLComponent<"span"> = (props, children) => { return h("span", props, children); }
export const Strong: HTMLComponent<"strong"> = (props, children) => { return h("strong", props, children); }
export const Style: HTMLComponent<"style"> = (props, children) => { return h("style", props, children); }
export const Sub: HTMLComponent<"sub"> = (props, children) => { return h("sub", props, children); }
export const Summary: HTMLComponent<"summary"> = (props, children) => { return h("summary", props, children); }
export const Sup: HTMLComponent<"sup"> = (props, children) => { return h("sup", props, children); }
export const Table: HTMLComponent<"table"> = (props, children) => { return h("table", props, children); }
export const Tbody: HTMLComponent<"tbody"> = (props, children) => { return h("tbody", props, children); }
export const Td: HTMLComponent<"td"> = (props, children) => { return h("td", props, children); }
export const Template: HTMLComponent<"template"> = (props, children) => { return h("template", props, children); }
export const Textarea: HTMLComponent<"textarea"> = (props, children) => { return h("textarea", props, children); }
export const Tfoot: HTMLComponent<"tfoot"> = (props, children) => { return h("tfoot", props, children); }
export const Th: HTMLComponent<"th"> = (props, children) => { return h("th", props, children); }
export const Thead: HTMLComponent<"thead"> = (props, children) => { return h("thead", props, children); }
export const Time: HTMLComponent<"time"> = (props, children) => { return h("time", props, children); }
export const Title: HTMLComponent<"title"> = (props, children) => { return h("title", props, children); }
export const Tr: HTMLComponent<"tr"> = (props, children) => { return h("tr", props, children); }
export const Track: HTMLComponent<"track"> = (props, children) => { return h("track", props, children); }
export const U: HTMLComponent<"u"> = (props, children) => { return h("u", props, children); }
export const Ul: HTMLComponent<"ul"> = (props, children) => { return h("ul", props, children); }
export const Var: HTMLComponent<"var"> = (props, children) => { return h("var", props, children); }
export const Video: HTMLComponent<"video"> = (props, children) => { return h("video", props, children); }
export const Wbr: HTMLComponent<"wbr"> = (props, children) => { return h("wbr", props, children); }
