import { h } from "./h";
import { DoomProperties } from "./types";

export function A(props?: DoomProperties<"a">) { return h("a", props); }
export function Abbr(props?: DoomProperties<"abbr">) { return h("abbr", props); }
export function Address(props?: DoomProperties<"address">) { return h("address", props); }
export function Area(props?: DoomProperties<"area">) { return h("area", props); }
export function Article(props?: DoomProperties<"article">) { return h("article", props); }
export function Aside(props?: DoomProperties<"aside">) { return h("aside", props); }
export function Audio(props?: DoomProperties<"audio">) { return h("audio", props); }
export function B(props?: DoomProperties<"b">) { return h("b", props); }
export function Base(props?: DoomProperties<"base">) { return h("base", props); }
export function Bdi(props?: DoomProperties<"bdi">) { return h("bdi", props); }
export function Bdo(props?: DoomProperties<"bdo">) { return h("bdo", props); }
export function Blockquote(props?: DoomProperties<"blockquote">) { return h("blockquote", props); }
export function Body(props?: DoomProperties<"body">) { return h("body", props); }
export function Br(props?: DoomProperties<"br">) { return h("br", props); }
export function Button(props?: DoomProperties<"button">) { return h("button", props); }
export function Canvas(props?: DoomProperties<"canvas">) { return h("canvas", props); }
export function Caption(props?: DoomProperties<"caption">) { return h("caption", props); }
export function Cite(props?: DoomProperties<"cite">) { return h("cite", props); }
export function Code(props?: DoomProperties<"code">) { return h("code", props); }
export function Col(props?: DoomProperties<"col">) { return h("col", props); }
export function Colgroup(props?: DoomProperties<"colgroup">) { return h("colgroup", props); }
export function Data(props?: DoomProperties<"data">) { return h("data", props); }
export function Datalist(props?: DoomProperties<"datalist">) { return h("datalist", props); }
export function Dd(props?: DoomProperties<"dd">) { return h("dd", props); }
export function Del(props?: DoomProperties<"del">) { return h("del", props); }
export function Details(props?: DoomProperties<"details">) { return h("details", props); }
export function Dfn(props?: DoomProperties<"dfn">) { return h("dfn", props); }
export function Dialog(props?: DoomProperties<"dialog">) { return h("dialog", props); }
export function Div(props?: DoomProperties<"div">) { return h("div", props); }
export function Dl(props?: DoomProperties<"dl">) { return h("dl", props); }
export function Dt(props?: DoomProperties<"dt">) { return h("dt", props); }
export function Em(props?: DoomProperties<"em">) { return h("em", props); }
export function Embed(props?: DoomProperties<"embed">) { return h("embed", props); }
export function Fieldset(props?: DoomProperties<"fieldset">) { return h("fieldset", props); }
export function Figcaption(props?: DoomProperties<"figcaption">) { return h("figcaption", props); }
export function Figure(props?: DoomProperties<"figure">) { return h("figure", props); }
export function Footer(props?: DoomProperties<"footer">) { return h("footer", props); }
export function Form(props?: DoomProperties<"form">) { return h("form", props); }
export function H1(props?: DoomProperties<"h1">) { return h("h1", props); }
export function H2(props?: DoomProperties<"h2">) { return h("h2", props); }
export function H3(props?: DoomProperties<"h3">) { return h("h3", props); }
export function H4(props?: DoomProperties<"h4">) { return h("h4", props); }
export function H5(props?: DoomProperties<"h5">) { return h("h5", props); }
export function H6(props?: DoomProperties<"h6">) { return h("h6", props); }
export function Head(props?: DoomProperties<"head">) { return h("head", props); }
export function Header(props?: DoomProperties<"header">) { return h("header", props); }
export function Hgroup(props?: DoomProperties<"hgroup">) { return h("hgroup", props); }
export function Hr(props?: DoomProperties<"hr">) { return h("hr", props); }
export function Html(props?: DoomProperties<"html">) { return h("html", props); }
export function I(props?: DoomProperties<"i">) { return h("i", props); }
export function Iframe(props?: DoomProperties<"iframe">) { return h("iframe", props); }
export function Img(props?: DoomProperties<"img">) { return h("img", props); }
export function Input(props?: DoomProperties<"input">) { return h("input", props); }
export function Ins(props?: DoomProperties<"ins">) { return h("ins", props); }
export function Kbd(props?: DoomProperties<"kbd">) { return h("kbd", props); }
export function Label(props?: DoomProperties<"label">) { return h("label", props); }
export function Legend(props?: DoomProperties<"legend">) { return h("legend", props); }
export function Li(props?: DoomProperties<"li">) { return h("li", props); }
export function Link(props?: DoomProperties<"link">) { return h("link", props); }
export function Main(props?: DoomProperties<"main">) { return h("main", props); }
export function Map(props?: DoomProperties<"map">) { return h("map", props); }
export function Mark(props?: DoomProperties<"mark">) { return h("mark", props); }
export function Menu(props?: DoomProperties<"menu">) { return h("menu", props); }
export function Meta(props?: DoomProperties<"meta">) { return h("meta", props); }
export function Meter(props?: DoomProperties<"meter">) { return h("meter", props); }
export function Nav(props?: DoomProperties<"nav">) { return h("nav", props); }
export function Noscript(props?: DoomProperties<"noscript">) { return h("noscript", props); }
export function Ol(props?: DoomProperties<"ol">) { return h("ol", props); }
export function Optgroup(props?: DoomProperties<"optgroup">) { return h("optgroup", props); }
export function Option(props?: DoomProperties<"option">) { return h("option", props); }
export function Output(props?: DoomProperties<"output">) { return h("output", props); }
export function P(props?: DoomProperties<"p">) { return h("p", props); }
export function Picture(props?: DoomProperties<"picture">) { return h("picture", props); }
export function Pre(props?: DoomProperties<"pre">) { return h("pre", props); }
export function Progress(props?: DoomProperties<"progress">) { return h("progress", props); }
export function Q(props?: DoomProperties<"q">) { return h("q", props); }
export function Rp(props?: DoomProperties<"rp">) { return h("rp", props); }
export function Rt(props?: DoomProperties<"rt">) { return h("rt", props); }
export function Ruby(props?: DoomProperties<"ruby">) { return h("ruby", props); }
export function S(props?: DoomProperties<"s">) { return h("s", props); }
export function Samp(props?: DoomProperties<"samp">) { return h("samp", props); }
export function Script(props?: DoomProperties<"script">) { return h("script", props); }
export function Section(props?: DoomProperties<"section">) { return h("section", props); }
export function Select(props?: DoomProperties<"select">) { return h("select", props); }
export function Slot(props?: DoomProperties<"slot">) { return h("slot", props); }
export function Small(props?: DoomProperties<"small">) { return h("small", props); }
export function Source(props?: DoomProperties<"source">) { return h("source", props); }
export function Span(props?: DoomProperties<"span">) { return h("span", props); }
export function Strong(props?: DoomProperties<"strong">) { return h("strong", props); }
export function Style(props?: DoomProperties<"style">) { return h("style", props); }
export function Sub(props?: DoomProperties<"sub">) { return h("sub", props); }
export function Summary(props?: DoomProperties<"summary">) { return h("summary", props); }
export function Sup(props?: DoomProperties<"sup">) { return h("sup", props); }
export function Table(props?: DoomProperties<"table">) { return h("table", props); }
export function Tbody(props?: DoomProperties<"tbody">) { return h("tbody", props); }
export function Td(props?: DoomProperties<"td">) { return h("td", props); }
export function Template(props?: DoomProperties<"template">) { return h("template", props); }
export function Textarea(props?: DoomProperties<"textarea">) { return h("textarea", props); }
export function Tfoot(props?: DoomProperties<"tfoot">) { return h("tfoot", props); }
export function Th(props?: DoomProperties<"th">) { return h("th", props); }
export function Thead(props?: DoomProperties<"thead">) { return h("thead", props); }
export function Time(props?: DoomProperties<"time">) { return h("time", props); }
export function Title(props?: DoomProperties<"title">) { return h("title", props); }
export function Tr(props?: DoomProperties<"tr">) { return h("tr", props); }
export function Track(props?: DoomProperties<"track">) { return h("track", props); }
export function U(props?: DoomProperties<"u">) { return h("u", props); }
export function Ul(props?: DoomProperties<"ul">) { return h("ul", props); }
export function Var(props?: DoomProperties<"var">) { return h("var", props); }
export function Video(props?: DoomProperties<"video">) { return h("video", props); }
export function Wbr(props?: DoomProperties<"wbr">) { return h("wbr", props); }
